apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processor
  namespace: quantum-access-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processor
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
      - name: data-processor
        image: arm64v8/python:3.9-alpine
        command:
        - sh
        - -c
        - apk add --no-cache gcc musl-dev && pip install paho-mqtt requests && python -u /app/data_processor.py
        env:
        - name: MQTT_BROKER
          value: "mqtt-broker.quantum-access-control.svc.cluster.local"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_TOPIC
          value: "qsensor/#"
        - name: ORION_HOST
          value: "orion-context-broker.quantum-access-control.svc.cluster.local"
        - name: ORION_PORT
          value: "1026"
        resources:
          limits:
            memory: 256Mi
            cpu: "0.2"
          requests:
            memory: 128Mi
            cpu: "0.1"
        volumeMounts:
        - name: code-volume
          mountPath: /app
      volumes:
      - name: code-volume
        configMap:
          name: data-processor-code
