apiVersion: v1
kind: Service
metadata:
  name: apache-nifi
  namespace: quantum-access-control
spec:
  selector:
    app: apache-nifi
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
