apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: quantum-access-control
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
    name: rest
  - port: 9300
    targetPort: 9300
    name: inter-node
  selector:
    app: elasticsearch
  type: ClusterIP
