apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-pvc
  namespace: quantum-access-control
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
