apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-pvc
  namespace: quantum-access-control
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
