apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-nifi
  namespace: quantum-access-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-nifi
  template:
    metadata:
      labels:
        app: apache-nifi
    spec:
      containers:
      - name: apache-nifi
        image: emqx/nifi:1.13.2-arm64v8
        ports:
        - containerPort: 8080
        env:
        - name: NIFI_WEB_HTTP_PORT
          value: "8080"
        - name: NIFI_WEB_HTTP_HOST
          value: "0.0.0.0"
        - name: NIFI_JVM_HEAP_INIT
          value: "256m"
        - name: NIFI_JVM_HEAP_MAX
          value: "512m"
        resources:
          limits:
            memory: 768Mi
            cpu: "0.3"
          requests:
            memory: 256Mi
            cpu: "0.1"
        volumeMounts:
        - name: nifi-conf
          mountPath: /opt/nifi/nifi-current/conf
        - name: nifi-content
          mountPath: /opt/nifi/nifi-current/content_repository
        - name: nifi-database
          mountPath: /opt/nifi/nifi-current/database_repository
        - name: nifi-flowfile
          mountPath: /opt/nifi/nifi-current/flowfile_repository
        - name: nifi-provenance
          mountPath: /opt/nifi/nifi-current/provenance_repository
        - name: nifi-state
          mountPath: /opt/nifi/nifi-current/state
      volumes:
      - name: nifi-conf
        emptyDir: {}
      - name: nifi-content
        emptyDir: {}
      - name: nifi-database
        emptyDir: {}
      - name: nifi-flowfile
        emptyDir: {}
      - name: nifi-provenance
        emptyDir: {}
      - name: nifi-state
        emptyDir: {}
