apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: quantum-access-control
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "/etc/prometheus/rules.yml"

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          # - alertmanager:9093

    scrape_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - source_labels: [__address__]
          regex: '(.*):10250'
          replacement: '${1}:10255'
          target_label: __address__

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name

      - job_name: 'esp32-simulator'
        static_configs:
        - targets: ['esp32-simulator:9100']

      - job_name: 'raspberry-pi-gateway'
        static_configs:
        - targets: ['raspberry-pi-gateway:9100']

      - job_name: 'orion-context-broker'
        static_configs:
        - targets: ['orion-context-broker:1026']

      - job_name: 'draco'
        static_configs:
        - targets: ['draco:5050']
