apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-pvc
  namespace: quantum-access-control
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
