apiVersion: apps/v1
kind: Deployment
metadata:
  name: raspberry-pi-gateway
  namespace: quantum-access-control
  labels:
    app: raspberry-pi-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raspberry-pi-gateway
  template:
    metadata:
      labels:
        app: raspberry-pi-gateway
    spec:
      containers:
      - name: mqtt-broker
        image: eclipse-mosquitto:2.0
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config
        - name: mosquitto-data
          mountPath: /mosquitto/data
        - name: mosquitto-log
          mountPath: /mosquitto/log
      - name: quantum-processor
        image: python:3.9-slim
        command: ["python", "-u", "/app/quantum_processor.py"]
        resources:
          limits:
            memory: 300Mi
            cpu: 200m
          requests:
            memory: 150Mi
            cpu: 50m
        env:
        - name: MQTT_BROKER
          valueFrom:
            configMapKeyRef:
              name: quantum-config
              key: mqtt-broker
        - name: MQTT_PORT
          valueFrom:
            configMapKeyRef:
              name: quantum-config
              key: mqtt-port
        - name: MQTT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: quantum-config
              key: mqtt-topic
        - name: ORION_HOST
          valueFrom:
            configMapKeyRef:
              name: quantum-config
              key: orion-host
        - name: ORION_PORT
          valueFrom:
            configMapKeyRef:
              name: quantum-config
              key: orion-port
        volumeMounts:
        - name: quantum-code
          mountPath: /app
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-data
        emptyDir: {}
      - name: mosquitto-log
        emptyDir: {}
      - name: quantum-code
        configMap:
          name: quantum-processor-code
